name: default_oracle

on:
  push:
    branches:
      - '*'
      - '**/*'
      - '!master'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest,macos-latest,windows-latest ]
        java: [ '17', '21' ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: ${{ matrix.java }}
          cache: 'maven'


      - name: Prepare mvnw
        run: chmod +x ./mvnw

      - name: Build
        run: ./mvnw clean package

