name: jacoco

on:
  push:
    branches:
      - '*'
      - '**/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'maven'

            
      - name: Prepare mvnw
        run: chmod +x ./mvnw

      - name: Build
        run: ./mvnw verify jacoco:report-aggregate -B -q

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: target/site/jacoco-aggregate/jacoco.xml
